# Generated by Django 5.2 on 2025-04-30 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidade', '0003_delete_usuario_alter_post_autor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='posts/'),
        ),
    ]
