# Generated by Django 5.2.1 on 2025-07-13 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comunidade", "0007_post_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="perfil",
            name="ultima_interacao",
            field=models.DateField(blank=True, null=True),
        ),
    ]
