# Generated by Django 5.2.1 on 2025-08-21 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comunidade", "0009_alter_post_tags"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comentario",
            options={"ordering": ["-data"]},
        ),
        migrations.AlterField(
            model_name="comentario",
            name="data",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
